Repository bonitasoft/bonita-application-directory, pull requests merged in 2021-04, with the labels that each got.

#6 feat (application directory): Add error pages into the application directory
  applications/bonita-application-directory.xml
  pom.xml
Labels: enhancement

#8 feat(app directory): Add new zip packaging to application
  applications/bonita-application-directory.png
  applications/bonita-application-directory.xml
  bos-assembly.xml
  pom.xml
  zip-assembly.xml
Labels: Review done

#10 feat(packaging): use pages sources artifact instead of rebuilding it
  pom.xml
Labels: Review needed
