Repository bonitasoft/bonita-application-directory, pull requests merged in 2024-03, with the labels that each got.

#38 chore (CI) migrate build github actions
  .github/workflows/_reusable_build.yml
  .github/workflows/build_pr.yml
Labels: Review done

#42 [merge] 7.14.x into 7.15.x
  .github/workflows/_reusable_build.yml
  .github/workflows/all_check_passed.yml
  .github/workflows/build.yml
  .github/workflows/build_pr.yml
  .github/workflows/create_merge_pr_upstream.yml
  Jenkinsfile
Labels: automerge

#45 [merge] 7.14.x into 7.15.x
  .github/workflows/_reusable_build.yml
  .github/workflows/build_pr.yml
  pom.xml
Labels: automerge

#43 [merge] 7.15.x into 8.0.x
  .github/workflows/_reusable_build.yml
  .github/workflows/all_check_passed.yml
  .github/workflows/build.yml
  .github/workflows/build_pr.yml
  .github/workflows/create_merge_pr_upstream.yml
  Jenkinsfile
  pom.xml
Labels: automerge

#47 [merge] 8.0.x into master
  .github/workflows/_reusable_build.yml
  .github/workflows/all_check_passed.yml
  .github/workflows/build.yml
  .github/workflows/build_pr.yml
  .github/workflows/create_merge_pr_upstream.yml
  Jenkinsfile
  pom.xml
Labels: automerge

#48 [merge] master into release-10.0.0
  .github/workflows/_reusable_build.yml
  .github/workflows/all_check_passed.yml
  .github/workflows/build.yml
  .github/workflows/build_pr.yml
  .github/workflows/create_merge_pr_upstream.yml
  Jenkinsfile
  pom.xml
Labels: automerge

#52 [merge] 7.14.x into 7.15.x
  .github/workflows/build_pr.yml
Labels: automerge

#53 [merge] 7.15.x into 8.0.x
  .github/workflows/build_pr.yml
Labels: automerge

#54 [merge] 8.0.x into master
  .github/workflows/build_pr.yml
Labels: automerge

#55 [merge] master into release-10.0.0
  .github/workflows/build_pr.yml
Labels: automerge

#56 [merge] release-10.0.0 into dev
  .github/workflows/build_pr.yml
Labels: automerge

#58 [merge] 7.14.x into 7.15.x
  .github/workflows/build_pr.yml
Labels: automerge

#59 [merge] 7.15.x into 8.0.x
  .github/workflows/build_pr.yml
Labels: automerge

#60 [merge] 8.0.x into master
  .github/workflows/build_pr.yml
Labels: automerge

#61 [merge] master into release-10.0.0
  .github/workflows/build_pr.yml
Labels: automerge

#62 [merge] release-10.0.0 into dev
  .github/workflows/build_pr.yml
Labels: automerge

#64 [merge] release-10.0.0 into dev
  .github/workflows/_reusable_build.yml
Labels: automerge

#66 [merge] 7.14.x into 7.15.x
  bos-distrib/pom.xml
Labels: automerge

#67 [merge] 7.15.x into 8.0.x
  bos-distrib/pom.xml
Labels: automerge

#71 [merge] master into release-10.0.0
  src/main/resources/bos-distrib/pom.xml
Labels: automerge

#73 [merge] release-10.0.0 into dev
  src/main/resources/bos-distrib/pom.xml
Labels: automerge

#69 CI(tag): reusable tag
  .github/workflows/_reusable_tag.yml
Labels: Review needed

#74 [merge] 7.14.x into 7.15.x
  .github/workflows/_reusable_tag.yml
Labels: automerge

#75 [merge] 7.15.x into 8.0.x
  .github/workflows/_reusable_tag.yml
Labels: automerge

#78 [merge] 7.14.x into 7.15.x
  .github/workflows/_reusable_build.yml
  .github/workflows/_reusable_tag.yml
Labels: automerge

#79 [merge] 7.15.x into 8.0.x
  .github/workflows/_reusable_build.yml
  .github/workflows/_reusable_tag.yml
Labels: automerge

#80 [merge] master into release-10.0.0
  .github/workflows/_reusable_build.yml
  .github/workflows/_reusable_tag.yml
Labels: automerge

#81 [merge] release-10.0.0 into dev
  .github/workflows/_reusable_build.yml
  .github/workflows/_reusable_tag.yml
Labels: automerge

#84 [merge] release-10.0.0 into dev
  pom.xml
Labels: automerge
